### ISSUE TITLE
Intermittent authentication errors leading to auth failure for 3+ days

### ISSUE THREAD

**Issue by working-name** [standardnotes/standalone#15]
**Describe the issue**
I'm self-hosting this with portainer and it's been going well for the past two months I think. Well in the sense that I kept getting `invalid authentication. please try again` every few times. Usually closing the electron app down and re-starting it made it work. Sometimes it would require a couple hours. However, for the past 3 days I can't log in.

No chance of someone breaching the container or guessing my email/password combination - it's nasty long and ugly.

Other than upgrading the electron app as it comes from Fedora 34, no other changes. Containers have been up ever since I first set it up. I've restarted containers, same deal. No portainer updates, nothing. No network changes, and I'm accessing it internally anyway (as you can see from the logs).

**Service Versions (please complete the following information):**

I have no clue how to get these things from the containers. Is there a command I can run? I grepped the files for version and I didn't see anything related.

 - syncing-server-js: ?
 - auth: ?
 - api-gateway: ?

**Logs**

```

2021-06-30T01:53:19.708795313Z {"message":"Calling [POST] http://syncing-server:3000/items/sync,\n        headers: {\"connection\":\"upgrade\",\"host\":\"standardnotes.domain.name\",\"x-real-ip\":\"10.0.0.1\",\"x-forwarded-for\":\"10.0.0.1\",\"x-forwarded-proto\":\"https\",\"content-length\":\"113\",\"authorization\":\"Bearer 1:e98a3e38-79e9-4b2c-8dc1-aa625c734683:froyDaCklUKsguU-Hw2WLQ\",\"user-agent\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) StandardNotes/3.8.10 Chrome/83.0.4103.122 Electron/9.4.3 Safari/537.36\",\"content-type\":\"application/json\",\"accept\":\"*/*\",\"sec-fetch-site\":\"cross-site\",\"sec-fetch-mode\":\"cors\",\"sec-fetch-dest\":\"empty\",\"accept-encoding\":\"gzip, deflate, br\",\"accept-language\":\"en-US\"},\n        query: {},\n        payload: {\"items\":[],\"sync_token\":\"MjoxNjI0NzQyNDI0LjA4ODAyODc=\\n\",\"compute_integrity\":false,\"limit\":150,\"api\":\"20200115\"}","level":"debug"},
2021-06-30T01:53:19.719818602Z {"meta":{"req":{"url":"/items/sync","headers":{"connection":"upgrade","x-real-ip":"10.0.0.1","x-forwarded-for":"10.0.0.1","x-forwarded-proto":"https","content-length":"113","authorization":"Bearer 1:e98a3e38-79e9-4b2c-8dc1-aa625c734683:froyDaCklUKsguU-Hw2WLQ","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) StandardNotes/3.8.10 Chrome/83.0.4103.122 Electron/9.4.3 Safari/537.36","content-type":"application/json","accept":"*/*","sec-fetch-site":"cross-site","sec-fetch-mode":"cors","sec-fetch-dest":"empty","accept-encoding":"gzip, deflate, br","accept-language":"en-US"},"method":"POST","httpVersion":"1.0","originalUrl":"/items/sync","query":{}},"res":{"statusCode":401},"responseTime":11},"level":"info","message":"HTTP POST /items/sync"},
2021-06-30T01:53:19.720556542Z Error: Unauthorized,
2021-06-30T01:53:19.720577528Z     at Request.callback (/var/www/node_modules/superagent/lib/node/index.js:883:15),
2021-06-30T01:53:19.720586259Z     at /var/www/node_modules/superagent/lib/node/index.js:1127:20,
2021-06-30T01:53:19.720631815Z     at IncomingMessage.<anonymous> (/var/www/node_modules/superagent/lib/node/parsers/json.js:22:7),
2021-06-30T01:53:19.720648275Z     at Unzip.<anonymous> (/var/www/node_modules/superagent/lib/node/unzip.js:53:12),
2021-06-30T01:53:19.720640838Z     at Stream.emit (events.js:315:20),
2021-06-30T01:53:19.720655990Z     at Unzip.emit (events.js:315:20),
2021-06-30T01:53:19.720663517Z     at endReadableNT (_stream_readable.js:1327:12),
2021-06-30T01:53:19.720670872Z     at processTicksAndRejections (internal/process/task_queues.js:80:21),
2021-06-30T01:53:19.708640556Z {"level":"debug","message":"Calling legacy syncing server on: /items/sync"}

```

Can't see anything interesting with docker logs for the other containers. Any ideas?

**Comment by mobitar** [comment]
Most likely this is a mismatch between client and servers being on different versions. Our clients recently have underwent a lot of changes regarding API infrastructure, so if you're using all the latest clients, you need to make sure you're also using the latest version of the server.

**Comment by working-name** [comment]
@mobitar Cool, you were right, I started an older AppImage and it's fine. It would have been super great if the client would say "yo, your server is old, needs an update" but finding out via a github issue is just as fine. 

Thanks for the hint!

**Comment by working-name** [comment]
Spoke a bit too soon I guess :( 
`api-gateway_1               | {"message":"Could not pass the request to underlying services: connect ECONNREFUSED 172.19.0.8:3000","level":"error"}` looks like api-gateway's config is hardwired wrong. The IP is .4 not .8 for port 3000.

**Comment by mobitar** [comment]
Not sure, but be sure to kill and restart all containers. That's probably when ports are allocated. cc @karolsojko

**Comment by working-name** [comment]
Me neither, I already killed everything and restarted. Might need to remove images and data, start fresh. Not looking forward to doing that :(

**Comment by karolsojko** [comment]
Hi @working-name 

> I have no clue how to get these things from the containers. Is there a command I can run? I grepped the files for version and I didn't see anything related.

can you open your `docker-compose.yml` file and check what versions the services have there?

Also are you using this repo `standalone` or the `syncing-server-js` one ?

**Comment by working-name** [comment]
Hello!

I probably downloaded a zip of master and plopped it onto RancherOS (runs portainer) - given the folder name 'syncing-server-master'. It should be the regular, not `-js`

```yaml
version: '3.8'
services:
  api-gateway:
    image: standardnotes/api-gateway
    env_file: docker/api-gateway.env
    environment:
      PORT: 3000
    entrypoint: ["./wait-for.sh", "syncing-server", "3000", "./wait-for.sh", "syncing-server-js", "3000", "./docker/entrypoint.sh", "start-web"]
    ports:
     - 3000:${EXPOSED_PORT}
    networks:
      syncing_server: {}
 
  auth:
    image: standardnotes/auth
    entrypoint: ["./wait-for.sh", "syncing-server-js", "3000", "./docker/entrypoint.sh", "start-worker"]
    env_file: docker/auth.env
    networks:
      syncing_server: {}
 
  syncing-server-js:
    image: standardnotes/syncing-server-js
    entrypoint: ["./wait-for.sh", "syncing-server", "3000", "./docker/entrypoint.sh", "start-web"]
    env_file: docker/syncing-server-js.env
    networks:
      syncing_server: {}
 
  syncing-server-js-worker:
    image: standardnotes/syncing-server-js
    entrypoint: ["./wait-for.sh", "syncing-server-js", "3000", "./docker/entrypoint.sh", "start-worker"]
    env_file: docker/syncing-server-js.env
    networks:
      syncing_server: {}
 
  syncing-server:
    build: .
    entrypoint: ["./wait-for.sh", "db", "3306", "./wait-for.sh", "cache", "6379", "./docker/entrypoint.sh", "start-local"]
    env_file: .env
    restart: unless-stopped
    environment:
      DB_HOST: db
      REDIS_URL: redis://cache:6379
    networks:
      standardnotes_proxy:
        aliases:
         - syncing_server
      syncing_server: {}
    volumes:
     - .:/syncing-server
 
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
     - 3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
     - ./data:/var/lib/mysql
    networks:
     - syncing_server
 
  cache:
    image: redis:6.0-alpine
    volumes:
     - ./cache:/data
    ports:
     - 6379
    networks:
     - syncing_server
 
networks:
  syncing_server:
    name: syncing_server
  standardnotes_proxy:
    name: standardnotes
```

I'm not sure how to figure out why it resolves syncing-server-js to a different IP from within api-gateway container. From the very last part of the startup sequence logs:

```py
api-gateway_1               | {"message":"Server started on port 3000","level":"info"}
syncing-server-js-worker_1  | syncing-server-js (172.19.0.3:3000) open # notice how this says .3
syncing-server-js-worker_1  | syncing-server-js:3000 is up - executing command
syncing-server-js-worker_1  | Starting Worker...
syncing-server-js-worker_1  | yarn run v1.22.5
syncing-server-js-worker_1  | $ node dist/bin/worker.js
syncing-server-js-worker_1  | New Relic for Node.js was unable to bootstrap itself due to an error:
syncing-server-js-worker_1  | Error: New Relic requires that you name this application!
syncing-server-js-worker_1  | Set app_name in your newrelic.js file or set environment variable
syncing-server-js-worker_1  | NEW_RELIC_APP_NAME. Not starting!
syncing-server-js-worker_1  |     at createAgent (/var/www/node_modules/newrelic/index.js:145:11)
syncing-server-js-worker_1  |     at initialize (/var/www/node_modules/newrelic/index.js:84:15)
syncing-server-js-worker_1  |     at Object.<anonymous> (/var/www/node_modules/newrelic/index.js:37:3)
syncing-server-js-worker_1  |     at Module._compile (node:internal/modules/cjs/loader:1092:14)
syncing-server-js-worker_1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
syncing-server-js-worker_1  |     at Module.load (node:internal/modules/cjs/loader:972:32)
syncing-server-js-worker_1  |     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
syncing-server-js-worker_1  |     at Module.require (node:internal/modules/cjs/loader:996:19)
syncing-server-js-worker_1  |     at require (node:internal/modules/cjs/helpers:92:18)
syncing-server-js-worker_1  |     at Object.<anonymous> (/var/www/dist/bin/worker.js:4:1)
syncing-server-js-worker_1  | {"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"2832acf4ff4a","pid":34,"time":"2021-07-01T13:49:01.545Z","msg":"Unable to find configuration file. If a configuration file is desired (common for non-containerized environments), a base configuration file can be copied from /var/www/node_modules/newrelic/newrelic.js and renamed to \"newrelic.js\" in the directory from which you will start your application. Attempting to start agent using environment variables."}
syncing-server-js-worker_1  | {"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"2832acf4ff4a","pid":34,"time":"2021-07-01T13:49:02.124Z","msg":"Unable to find configuration file. If a configuration file is desired (common for non-containerized environments), a base configuration file can be copied from /var/www/node_modules/@standardnotes/domain-events/node_modules/newrelic/newrelic.js and renamed to \"newrelic.js\" in the directory from which you will start your application. Attempting to start agent using environment variables."}
syncing-server-js-worker_1  | {"message":"Starting worker...","level":"info"}
api-gateway_1               | {"message":"Could not pass the request to underlying services: connect ECONNREFUSED 172.19.0.4:3000","level":"error"} # and then here it tries .4 vs .3
api-gateway_1               | {"level":"debug","message":"Response error: Error: connect ECONNREFUSED 172.19.0.4:3000\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16) {\n  errno: -111,\n  code: 'ECONNREFUSED',\n  syscall: 'connect',\n  address: '172.19.0.4',\n  port: 3000,\n  response: undefined\n}"}
```
