### ISSUE TITLE
[BUG] API not passing requests to authentication - Could not pass the request to underlying services: connect ETIMEDOUT

### ISSUE THREAD

**Issue by eric-pierce** [standardnotes/standalone#18]
**Describe the bug**
The API Gateway appears to be dropping all requests

**To Reproduce**
1. Try to authenticate or sync

**Logs**
```
snapi                 | snauth:3002 is unavailable yet - waiting for it to start
snapi                 | snauth:3002 is unavailable yet - waiting for it to start
snapi                 | snauth (172.18.0.17:3002) open
snapi                 | snauth:3002 is up - executing command
snapi                 | snsync (172.18.0.6:3000) open
snapi                 | snsync:3000 is up - executing command
snapi                 | Starting Web...
snapi                 | yarn run v1.22.5
snapi                 | $ node dist/bin/server.js
snapi                 | {"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"7a001252817b","pid":34,"time":"2021-07-10T18:38:12.718Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
snapi                 | routes: 
snapi                 |   - 
snapi                 |     controller: WebSocketsController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: POST /v1/sockets/
snapi                 |       - 
snapi                 |         route: DELETE /v1/sockets/
snapi                 |   - 
snapi                 |     controller: PaymentsController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: GET /v1/downloads
snapi                 |       - 
snapi                 |         route: GET /v1/downloads/download-info
snapi                 |       - 
snapi                 |         route: GET /v1/downloads/platforms
snapi                 |       - 
snapi                 |         route: GET /v1/help/categories
snapi                 |       - 
snapi                 |         route: GET /v1/knowledge/categories
snapi                 |       - 
snapi                 |         route: GET /v1/extensions
snapi                 |       - 
snapi                 |         route: ALL /v1/subscriptions(/*)?
snapi                 |       - 
snapi                 |         route: GET /v1/reset/validate
snapi                 |       - 
snapi                 |         route: DELETE /v1/reset
snapi                 |       - 
snapi                 |         route: POST /v1/reset
snapi                 |       - 
snapi                 |         route: POST /v1/user-registration
snapi                 |       - 
snapi                 |         route: POST /v1/admin/graphql
snapi                 |       - 
snapi                 |         route: POST /v1/admin/auth/login
snapi                 |       - 
snapi                 |         route: POST /v1/admin/auth/logout
snapi                 |       - 
snapi                 |         route: POST /v1/students
snapi                 |       - 
snapi                 |         route: POST /v1/students/:token/approve
snapi                 |       - 
snapi                 |         route: POST /v1/email_subscriptions/:token/less
snapi                 |       - 
snapi                 |         route: POST /v1/email_subscriptions/:token/more
snapi                 |       - 
snapi                 |         route: POST /v1/email_subscriptions/:token/mute/:campaignId
snapi                 |       - 
snapi                 |         route: POST /v1/email_subscriptions/:token/unsubscribe
snapi                 |       - 
snapi                 |         route: ALL /v1/pro_users(/*)?
snapi                 |       - 
snapi                 |         route: ALL /v1/refunds
snapi                 |   - 
snapi                 |     controller: ItemsController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: POST /v1/items/
snapi                 |   - 
snapi                 |     controller: RevisionsController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: GET /v1/items/:item_id/revisions/
snapi                 |       - 
snapi                 |         route: GET /v1/items/:item_id/revisions/:id
snapi                 |   - 
snapi                 |     controller: ActionsController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: POST /v1/login
snapi                 |       - 
snapi                 |         route: GET /v1/login-params
snapi                 |       - 
snapi                 |         route: POST /v1/logout
snapi                 |       - 
snapi                 |         route: GET /v1/auth/methods
snapi                 |   - 
snapi                 |     controller: UsersController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: PATCH /v1/users/:userId
snapi                 |       - 
snapi                 |         route: PUT /v1/users/:userId/password
snapi                 |       - 
snapi                 |         route: GET /v1/users/:userId/params
snapi                 |       - 
snapi                 |         route: ALL /v1/users/:userId/mfa
snapi                 |       - 
snapi                 |         route: POST /v1/users/
snapi                 |       - 
snapi                 |         route: PUT /v1/users/:userUuid/settings
snapi                 |       - 
snapi                 |         route: DELETE /v1/users/:userUuid/settings/:settingName
snapi                 |   - 
snapi                 |     controller: SessionsController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: GET /v1/sessions/
snapi                 |       - 
snapi                 |         route: DELETE /v1/sessions/:uuid
snapi                 |       - 
snapi                 |         route: DELETE /v1/sessions/
snapi                 |       - 
snapi                 |         route: POST /v1/sessions/refresh
snapi                 |   - 
snapi                 |     controller: HealthCheckController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: GET /healthcheck/
snapi                 |   - 
snapi                 |     controller: LegacyController
snapi                 |     endpoints: 
snapi                 |       - 
snapi                 |         route: POST /items/sync
snapi                 |       - 
snapi                 |         route: GET /items/:item_id/revisions
snapi                 |       - 
snapi                 |         route: GET /items/:item_id/revisions/:id
snapi                 |       - 
snapi                 |         route: GET /items/mfa/:userUuid
snapi                 |       - 
snapi                 |         route: DELETE /items/mfa/:userUuid
snapi                 |       - 
snapi                 |         route: ALL *
snapi                 | {"message":"Server started on port 3000","level":"info"}
snapi                 | {"message":"Could not pass the request to underlying services: connect ETIMEDOUT 0.0.11.186:80","level":"error"}
snapi                 | {"message":"Could not pass the request to underlying services: connect ETIMEDOUT 0.0.11.186:80","level":"error"}
snapi                 | {"message":"Could not pass the request to underlying services: connect ETIMEDOUT 0.0.11.186:80","level":"error"}
snapi                 | {"message":"Could not pass the request to underlying services: connect ETIMEDOUT 0.0.11.186:80","level":"error"}
snapi                 | {"message":"Could not pass the request to underlying services: connect ETIMEDOUT 0.0.11.186:80","level":"error"}
```
**Service Versions (please complete the following information):**
 - syncing-server-js: latest (dockerhub)
 - auth: latest (dockerhub)
 - api-gateway: latest (dockerhub)

**Additional context**
This setup working up until two days ago, when it stopped working. I have the containers updating to the latest version nightly.

The authentication issues occur on both web and ios clients.

**Relevant Docker-Compose Setup**
```
  snsync:
    container_name: snsync
    image: standardnotes/syncing-server-js:latest
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - mariadb
      - redis
    ports:
      - "127.0.0.1:3000:3000"
    entrypoint: [
      "./wait-for.sh", "mariadb", "3306",
      "./wait-for.sh", "redis", "6379",
      "./docker/entrypoint.sh", "start-web"
    ]
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - LOG_LEVEL=info
      - NODE_ENV=production
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - EXPOSED_PORT=8007
      - PORT=3000
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_REPLICA_HOST=mariadb
      - DB_DATABASE=standardnotes
      - DB_USERNAME=standardnotes
      - DB_PASSWORD=$MYSQL_STANDARDNOTES_PASSWORD
      - DB_DEBUG_LEVEL=all
      - DB_MIGRATIONS_PATH=dist/migrations/*.js
      - NEW_RELIC_ENABLED=false
      - NEW_RELIC_APP_NAME=Sync
      - NEW_RELIC_NO_CONFIG_FILE=true
      - REDIS_URL=redis://redis:$REDIS_PASSWORD@redis:6379
      - AUTH_SERVER_URL=snauth:3002
      - EMAIL_ATTACHMENT_MAX_BYTE_SIZE=10485760
      - REVISIONS_FREQUENCY=300

  snsync-worker:
    container_name: snsync-worker
    image: standardnotes/syncing-server-js:latest
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - mariadb
      - redis
      - snsync
    entrypoint: [
      "./wait-for.sh", "mariadb", "3306",
      "./wait-for.sh", "redis", "6379",
      "./wait-for.sh", "snsync", "3000",
      "./docker/entrypoint.sh", "start-worker"
    ]
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - LOG_LEVEL=info
      - NODE_ENV=production
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - EXPOSED_PORT=8007
      - PORT=3000
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_REPLICA_HOST=mariadb
      - DB_DATABASE=standardnotes
      - DB_USERNAME=standardnotes
      - DB_PASSWORD=$MYSQL_STANDARDNOTES_PASSWORD
      - DB_DEBUG_LEVEL=all
      - DB_MIGRATIONS_PATH=dist/migrations/*.js
      - NEW_RELIC_ENABLED=false
      - NEW_RELIC_APP_NAME=SyncWorker
      - NEW_RELIC_NO_CONFIG_FILE=true
      - REDIS_URL=redis://redis:$REDIS_PASSWORD@redis:6379
      - AUTH_SERVER_URL=snauth:3002
      - EMAIL_ATTACHMENT_MAX_BYTE_SIZE=10485760
      - REVISIONS_FREQUENCY=300

  snauth:
    container_name: snauth
    image: standardnotes/auth:latest
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - mariadb
      - redis
      - snsync
    ports:
      - "127.0.0.1:3002:3002"
    entrypoint: [
      "./wait-for.sh", "mariadb", "3306",
      "./wait-for.sh", "redis", "6379",
      "./wait-for.sh", "snsync", "3000",
      "./docker/entrypoint.sh", "start-web"
    ]
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - LOG_LEVEL=info
      - NODE_ENV=production
      - PORT=3002
      - JWT_SECRET=$JWT_SECRET
      - LEGACY_JWT_SECRET=$LEGACY_JWT_SECRET
      - PSEUDO_KEY_PARAMS_KEY=$PSEUDO_KEY_PARAMS_KEY
      - ENCRYPTION_SERVER_KEY=$ENCRYPTION_SERVER_KEY
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - SYNCING_SERVER_URL=snsync:3000
      - NEW_RELIC_ENABLED=false
      - NEW_RELIC_APP_NAME=Auth
      - NEW_RELIC_NO_CONFIG_FILE=true
      - REDIS_EVENTS_CHANNEL=auth-events
      - AUTH_JWT_TTL=60000
      - ACCESS_TOKEN_AGE=5184000
      - REFRESH_TOKEN_AGE=31556926
      - MAX_LOGIN_ATTEMPTS=6
      - FAILED_LOGIN_LOCKOUT=3600
      - EPHEMERAL_SESSION_AGE=259200
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_REPLICA_HOST=mariadb
      - DB_DATABASE=standardnotes
      - DB_USERNAME=standardnotes
      - DB_PASSWORD=$MYSQL_STANDARDNOTES_PASSWORD
      - DB_DEBUG_LEVEL=all
      - DB_MIGRATIONS_PATH=dist/migrations/*.js
      - REDIS_URL=redis://redis:$REDIS_PASSWORD@redis:6379
      - DISABLE_USER_REGISTRATION=true

  snauth-worker:
    container_name: snauth-worker
    image: standardnotes/auth:latest
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      - mariadb
      - redis
      - snauth
    entrypoint: [
      "./wait-for.sh", "mariadb", "3306",
      "./wait-for.sh", "redis", "6379",
      "./wait-for.sh", "snauth", "3002",
      "./docker/entrypoint.sh", "start-worker"
    ]
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - LOG_LEVEL=info
      - NODE_ENV=production
      - PORT=3002
      - JWT_SECRET=$JWT_SECRET
      - LEGACY_JWT_SECRET=$LEGACY_JWT_SECRET
      - PSEUDO_KEY_PARAMS_KEY=$PSEUDO_KEY_PARAMS_KEY
      - ENCRYPTION_SERVER_KEY=$ENCRYPTION_SERVER_KEY
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - SYNCING_SERVER_URL=snsync:3000
      - NEW_RELIC_ENABLED=false
      - NEW_RELIC_APP_NAME=AuthWorker
      - NEW_RELIC_NO_CONFIG_FILE=true
      - REDIS_EVENTS_CHANNEL=auth-events
      - AUTH_JWT_TTL=60000
      - ACCESS_TOKEN_AGE=5184000
      - REFRESH_TOKEN_AGE=31556926
      - MAX_LOGIN_ATTEMPTS=6
      - FAILED_LOGIN_LOCKOUT=3600
      - EPHEMERAL_SESSION_AGE=259200
      - DB_PORT=3306
      - DB_HOST=mariadb
      - DB_REPLICA_HOST=mariadb
      - DB_DATABASE=standardnotes
      - DB_USERNAME=standardnotes
      - DB_PASSWORD=$MYSQL_STANDARDNOTES_PASSWORD
      - DB_DEBUG_LEVEL=all
      - DB_MIGRATIONS_PATH=dist/migrations/*.js
      - REDIS_URL=redis://redis:$REDIS_PASSWORD@redis:6379
      - DISABLE_USER_REGISTRATION=true

  snapi:
    container_name: snapi
    image: standardnotes/api-gateway:latest
    restart: unless-stopped
    networks:
      - traefik
      - internal
    depends_on:
      - snsync
      - snauth
    entrypoint: [
      "./wait-for.sh", "snauth", "3002",
      "./wait-for.sh", "snsync", "3000",
      "./docker/entrypoint.sh", "start-web"
    ]
    ports:
      - 8007:3000
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - LOG_LEVEL=info
      - NODE_ENV=production
      - NEW_RELIC_ENABLED=false
      - NEW_RELIC_APP_NAME=APIGateway
      - NEW_RELIC_NO_CONFIG_FILE=true
      - SYNCING_SERVER_JS_URL=snsync:3000
      - AUTH_SERVER_URL=snauth:3002
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - PORT=3000
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.notesync-rtr.entrypoints=https"
      - "traefik.http.routers.notesync-rtr.rule=Host(`notesync.$DOMAINNAME`)"
      - "traefik.http.routers.notesync-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.notesync-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.notesync-rtr.middlewares=middlewares-standardnotes@file"
      ## HTTP Services
      - "traefik.http.routers.notesync-rtr.service=notesync-svc"
      - "traefik.http.services.notesync-svc.loadbalancer.server.port=3000"

  standardnotes:
    container_name: standardnotes
    image: standardnotes/web:stable
    restart: unless-stopped
    command: start-local
    networks:
      - traefik
    depends_on:
      - snsync
    ports:
      - 8010:3001
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - RAILS_ENV=development
      - PORT=3001
      - WEB_CONCURRENCY=0
      - SECRET_KEY_BASE=$STANDARD_NOTES_SECRET
      - APP_HOST=https://notes.$DOMAINNAME
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_LOG_TO_STDOUT=true
      - EXTENSIONS_MANAGER_LOCATION=extensions/extensions-manager/dist/index.html
      - BATCH_MANAGER_LOCATION=extensions/batch-manager/dist/index.min.html
      - SF_DEFAULT_SERVER=https://notesync.$DOMAINNAME
      - SF_NEXT_VERSION_SERVER=https://notesync.$DOMAINNAME
      - DATADOG_ENABLED=false
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.notes-rtr.entrypoints=https"
      - "traefik.http.routers.notes-rtr.rule=Host(`notes.$DOMAINNAME`)"
      - "traefik.http.routers.notes-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.notes-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.notes-rtr.service=notes-svc"
      - "traefik.http.services.notes-svc.loadbalancer.server.port=3001"
```
